sudo: required
services:
    - docker

before_install:
    - docker build -t manojselvin/docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true manojselvin/docker-react-app npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react-app"
    env: "docker-react-app-env"
    bucket_name: "elasticbeanstalk-ap-south-1-632516549497"
    bucket_path: "docker-react-app"
    on:
        branch: master
    access_key_id: 
        secure: "$AWS_ACCESS_KEY_ID"
    secret_access_key: 
        secure: "$AWS_SECRET_ACCESS_KEY"