sudo: required
services:
    - docker

before_install:
    - docker build -t manojselvin/docker-react-app -f Dockerfile.dev .

script:
    - docker run manojselvin/docker-react-app npm run test -- --coverage