version: '3'

services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        ports: 
            - '3000:3000'
        volumes: 
            - /var/www/html/react-app/node_modules
            - .:/var/www/html/react-app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        volumes: 
            - /var/www/html/react-app/node_modules
            - .:/var/www/html/react-app
        command: ["npm", "run", "test"]